### ISSUE TITLE
WIP for fixing WIP-0007 (or not) about data requests weight

### ISSUE THREAD

**Issue by lrubiorod** [witnet/WIPs#57]
https://github.com/witnet/WIPs/blob/master/wip-0007.md

**Comment by mariocao** [comment]
The PR https://github.com/witnet/witnet-rust/pull/1966 clarifies some of the DR weight formula parameters and removes a misplaced factor `alpha`. This PR does not change the logic as `alpha=1`. 😄 

I will open a WIP with an amendment for the WIP-0007 in order to match the current implementation with what was specified.

`DR_weight = DR_size*alpha + W*COMMIT + W*REVEAL*beta + TALLY*beta + (W+M)*OUTPUT_SIZE + N*INPUT_SIZE`

While in the WIP-0007 join transactions were highly subsidised by the protocol, the implementation was taking into account the weight of the transaction inputs.

This could create a wrong incentive to create DRs with the only purpose of joining UTXOs and, therefore, reducing the remaining block bucket for legit DRs. Nevertheless, join transactions are still possible by using regular VTTs where inputs weight is much less compared to the outputs.
